### ISSUE TITLE
M8: Final check on delivery of Software Bill of Materials

### ISSUE THREAD

**Issue by morganava** [blueprint-freespeech/gosling#120]
For this milestone we need to:
- [x] generate a SBOM for gosling 
- [x] release gosling beta
- [ ] fix any immediate issues that come out of the beta release

**Comment by morganava** [comment]
gosling crates SBOM now being generated and uploaded with each commit here:
- https://gosling.technology/gosling.spdx.json

Added in 52b938a02c357f1dc88cf876e8cc076f4c87d901

**Comment by morganava** [comment]
gosling 0.4.0 is now available for download -> https://crates.io/crates/gosling

Announcing next week in the 2024 state of the onion community day

**Comment by morganava** [comment]
No immediate issues have made themselves known
